Add dashboard templates for secondary-analysis.
HumanCellAtlas/dcp-monitoring pull request #10
Opened 2018-11-25 21:52 UTC by rexwangcc

This PR creates the dashboard templates for secondary-analysis following the instructions. The example dashboard is already on the dev Grafana instance named "analysis-staging".

I'm not sure about the correctness of the parameterization of the data sources in Terraform, so please point out if there is anything weird.

2018-11-26 21:17 UTC, mweiden approved these changes
@rexwangcc looks good! 👏 🚢

2018-11-27 22:38 UTC, samanehsan commented
@rexwangcc should the x-axis of this graph be the "Falcon-igniter-effective-release" metric? Right now it says "Falcon-Igniter-heartbeat": 
<img width="805" alt="screen shot 2018-11-27 at 5 34 13 pm" src="https://user-images.githubusercontent.com/6414394/49116230-f3784200-f26a-11e8-9c29-34cbee6956a5.png">

2018-11-28 16:24 UTC, rexwangcc commented
@samanehsan Sorry for the confusion, those are actually legends shown below the diagram :( I agree we should find a better name!

2018-11-28 21:51 UTC, rhiananthony commented
👍 Looks great to me!

2018-11-28 21:51 UTC, rhiananthony approved these changes

2018-11-28 21:55 UTC, mweiden requested changes
After looking over the dashboard itself in detail @rexwangcc and I came up with a few revisions to make it clearer. We should update this before shipping.

2018-11-29 22:41 UTC, rexwangcc commented
@mweiden I revised the analysis dashboard by merging your changes and taking suggestions I received from the DCP Demo audience, could you take another look at the current dashboard when you have a chance? Thanks!

2018-12-01 03:00 UTC, mweiden approved these changes

2018-12-01 03:04 UTC, mweiden commented
@rexwangcc I've rebased and tested this for you by uploading your dashboards. The `staging` dashboard works, but they `dev`, `integration`, and `prod` dashboards won't until you've given the service account `Monitoring Viewer` permissions for those accounts.

I have not deployed `prod`. Please use the steps outlined in https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md#deploying-a-module-into-an-environment and https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md#upload-to-grafana to complete the deployment to `prod`.

2018-12-01 03:04 UTC, merged

2018-12-03 00:13 UTC, rexwangcc commented
Thanks for deploying `staging`, `dev`, `integration` dashboards for us! I've verified that they work as expected by giving the right permission to the Grafana data source service account. Will try to deploy the dashboard for prod now.