Add a Grafana dashboard for Azul
HumanCellAtlas/dcp-monitoring pull request #12
Opened 2018-11-30 01:46 UTC by shiroyuki

(Related to https://github.com/DataBiosphere/azul/issues/59)

This PR is to add a Grafana dashboard for Azul.

2018-11-30 19:26 UTC, mweiden requested changes
Almost there!

Have you tried generating the json for this with `make apply` in an environment and uploading this to Grafana with `upload-to-grafana`? It would be good to confirm that your solution works before merging.

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +  "id": null,
Delete the `"id"` field. This will cause problems when you try to upload this.

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +            "Stage": "dev"
You need to template `Stage` with `var.env`

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +            "Stage": "dev"
Here too

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +            "Stage": "dev"
Here too

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +            "Stage": "dev"
Here too

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +            "Stage": "dev"
Here too

2018-11-30 19:26 UTC, mweiden commented on terraform/modules/env-dashboards/azul-dashboard.tf
> +            "Stage": "dev"
Here too

2018-11-30 19:38 UTC, shiroyuki commented
@mweiden I still can't do `make apply`. The updates on the issue is posted in the `#dcp-monitoring` channel.

2018-11-30 19:47 UTC, shiroyuki commented
@mweiden Can you help me running `make apply`?

2018-12-01 02:49 UTC, mweiden commented
@shiroyuki there were still some issues with this. I have fixed them for you. Please see them in 90e2c4b. I have confirmed the template to work. Please see the `staging` deployment below.

https://metrics.dev.data.humancellatlas.org/d/dcp-health-staging/azul-dashboard-staging?orgId=1

Please use the steps outlined in https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md#deploying-a-module-into-an-environment and https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md#upload-to-grafana to complete the deployment to `integration` and `prod`

2018-12-01 02:49 UTC, mweiden approved these changes

2018-12-01 02:49 UTC, merged

2018-12-03 18:36 UTC, shiroyuki commented
I just saw the changes. Thank you so much for your help.

2018-12-03 21:17 UTC, shiroyuki commented
@mweiden, about deployment to `integration` and `prod`, unfortunately I don't have permissions to do so. I think @hannes-ucsc will have to sort out how would deploy the dashboard to `integration` and `prod`.